# 参考
# * https://qiita.com/yukinarit/items/0996180032c077443efb
# * https://yiskw713.hatenablog.com/entry/2021/12/28/190000


name: wiki
# イベントトリガーの設定
on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
  pull_request: branches:
      - main
    paths:
      - "**/*.py"
  workflow_dispatch:

jobs:
  generate_pdoc:
    name: generating pdoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # set up python
      - name: Setting up python.
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # install poetry
      - name: Install Poetry
        run: pip install poetry

      # install dependencies
      - name: Install Dependencies
        run: poetry install --no-interaction

      # pdocでドキュメントを生成
      - name: Pdoc
        run: poetry run pdoc -t slack2python -o docs slack2python

      # 差分をgitにpushする
      # ref: https://zenn.dev/lollipop_onl/articles/eoz-gha-push-diffs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Wiki Generation by wiki.yml
          branch: gh-pages
          create_branch: true
          push_options: '--force'
